### ISSUE TITLE
AniSched-Desktop installation failed

### ISSUE THREAD

**Issue by skydtlee** [qkdxorjs1002/AniSched-Desktop#1]
Ask the app developer for a new app package. This one isn't signed with a trusted certificate (0x800B0100)

안녕하세요. 패키지 서명 되지 않았다고 설치가 되지 않네요.

**Comment by qkdxorjs1002** [comment]
@skydtlee 
MS 스토어 배포용으로, 서명을 하지 않아서 그럴겁니다. 
스토어에서 앱을 심사하고 있어서 추후에 스토어 링크 갱신하겠습니다. 
일단은 zip으로 압축된 것을 사용해주세요!

이슈는 닫지 않고 스토어 올라가면 코멘트 다시 한번 드리겠습니다.

**Comment by skydtlee** [comment]
> @skydtlee
> MS 스토어 배포용으로, 서명을 하지 않아서 그럴겁니다.
> 스토어에서 앱을 심사하고 있어서 추후에 스토어 링크 갱신하겠습니다.
> 일단은 zip으로 압축된 것을 사용해주세요!
> 
> 이슈는 닫지 않고 스토어 올라가면 코멘트 다시 한번 드리겠습니다.

감사합니다. 기다리고 있겠습니다!

**Comment by qkdxorjs1002** [comment]
@skydtlee 스토어 심사가 끝나서 등록이 완료되었습니다.
스토어 적용까지는 약간의 시간이 있을 수 있습니다.
[스토어 링크](https://www.microsoft.com/store/apps/9PB5WSXN3TMN)
