### ISSUE TITLE
애니시아 API 도메인 변경.

### ISSUE THREAD

**Issue by marker-seoul** [qkdxorjs1002/AniSched-Desktop#16]
https://github.com/anissia-net/document/blob/main/api_anime_schdule.md

애니시아의 프론트와 백엔드 서버 분리에 따라 API 도메인이 변경되었습니다.

기존 : https://anissia.net/api/*
변경 : https://api.anissia.net/*

준비가 완료되어 바로 적용하시면 됩니다.

Lable이 버그 밖에 없어서 버그로 남깁니다.

**Comment by marker-seoul** [comment]
https://github.com/qkdxorjs1002/AniSched-Android/issues/6
여기로 이동했습니다.

**Comment by qkdxorjs1002** [comment]
3.0.2
