### ISSUE TITLE
windows에서 스크롤 시 부드럽지 않고 적은 양만 스크롤 됨

### ISSUE THREAD

**Issue by ilsubyeega** [qkdxorjs1002/AniSched-Desktop#2]
브라우저 스크롤링과 다르게 마우스 스크롤을 하면 뚝뚝 스크롤 되고, 브라우저 대비 생각보다 적은 양만 스크롤됩니다.

https://user-images.githubusercontent.com/37479424/130334939-f42b4a25-45c2-4631-8fd0-4cf690433275.mp4

감사합니다.
+) mouse middle button으로도 이동이 불가능하네요

**Comment by qkdxorjs1002** [comment]
@ilsubyeega 
피드백 감사드리고 관련된 문제 확인했습니다.
일단은 클릭&드래그로 스크롤 해주세요. 다음 버전에서 수정해서 배포하겠습니다😊

**Comment by qkdxorjs1002** [comment]
4c896dc331c8e07939d69d7d8f7dad3cf85768d0

**Comment by qkdxorjs1002** [comment]
2.4.0

변경사항은 릴리즈 참고해주세요
